version: 2

sources:
  - name: rds
    freshness:
        warn_after:
            count: 24
            period: hour
        error_after:
            count: 36
            period: hour
    
    database: NORTHWINDS
    schema: public
    tables:
      - name: suppliers
        freshness:
            warn_after:
                count: 24
                period: hour
            error_after:
                count: 36
                period: hour
            filter: datediff('day', current_timestamp) < 2